/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesNewRouteImport } from './routes/articles/new'
import { Route as ArticlesIdRouteImport } from './routes/articles/$id'
import { Route as ArticlesIdEditRouteImport } from './routes/articles/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdEditRoute = ArticlesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ArticlesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/articles/$id' | '/articles/new' | '/articles/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/articles/$id' | '/articles/new' | '/articles/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/articles/$id'
    | '/articles/new'
    | '/articles/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesIdRoute: typeof ArticlesIdRouteWithChildren
  ArticlesNewRoute: typeof ArticlesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id/edit': {
      id: '/articles/$id/edit'
      path: '/edit'
      fullPath: '/articles/$id/edit'
      preLoaderRoute: typeof ArticlesIdEditRouteImport
      parentRoute: typeof ArticlesIdRoute
    }
  }
}

interface ArticlesIdRouteChildren {
  ArticlesIdEditRoute: typeof ArticlesIdEditRoute
}

const ArticlesIdRouteChildren: ArticlesIdRouteChildren = {
  ArticlesIdEditRoute: ArticlesIdEditRoute,
}

const ArticlesIdRouteWithChildren = ArticlesIdRoute._addFileChildren(
  ArticlesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesIdRoute: ArticlesIdRouteWithChildren,
  ArticlesNewRoute: ArticlesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
